# Generated by Django 5.2.1 on 2025-06-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_article_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
