# Generated by Django 5.2.1 on 2025-05-18 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="title",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="title",
            new_name="name",
        ),
    ]
